name: Funtional Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_crowdsec:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Install deps for tests
      run: pip install -r ./tests/requirements.txt && sudo apt install -y nftables
    - name: Run tests
      run: sudo -E env PATH=$PATH python3 -m unittest -v
